---

- name: Check if hbase is installed
  command: '{{ hbase_home_dir }}/bin/hbase version'
  ignore_errors: yes
  register: hbase_check

- name: download HBase release {{ hbase_release }}
  when: hbase_check.rc != 0
  get_url: url='http://archive.apache.org/dist/hbase/{{ hbase_release }}/{{ hbase_archive }}'
           dest='/home/vagrant/{{ hbase_archive }}'
           sha256sum='{{ hbase_sha256 }}'

- name: create HBase-related directories
  when: hbase_check.rc != 0
  file: path='{{ item }}' state=directory
  with_items:
    - '{{ hbase_data_dir }}'
    - '{{ zookeeper_data_dir }}'

- name: extract HBase archive
  when: hbase_check.rc != 0
  command: tar xzf '/home/vagrant/{{ hbase_archive }}'
           chdir=/home/vagrant/
           creates='{{ hbase_home_dir }}'

- name: symlink HBase home directory to just hbase/
  when: hbase_check.rc != 0
  file: path=/home/vagrant/hbase src='{{ hbase_home_dir }}' state=link

- name: write HBase config file
  when: hbase_check.rc != 0
  template: src=hbase-site.xml.j2
            dest='{{ hbase_home_dir }}/conf/hbase-site.xml'

- name: set JAVA_HOME environment variable for HBase
  when: hbase_check.rc != 0
  lineinfile: dest='{{ hbase_home_dir }}/conf/hbase-env.sh'
              regexp='^#?\s*export JAVA_HOME='
              line='export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre'
              state=present

- name: explicitly tell HBase to manage Zookeeper
  when: hbase_check.rc != 0
  lineinfile: dest='{{ hbase_home_dir }}/conf/hbase-env.sh'
              regexp='^#?\s*export HBASE_MANAGES_ZK='
              line='export HBASE_MANAGES_ZK=true'
              state=present

- name: start HBase
  when: hbase_check.rc != 0
  command: ./bin/start-hbase.sh
           chdir={{ hbase_home_dir }}
  register: hbase_start
  changed_when: hbase_start.stdout.find('starting master') == -1

- name: start Thrift server
  when: hbase_check.rc != 0
  command: ./bin/hbase-daemon.sh start thrift
           chdir={{ hbase_home_dir }}
  register: thrift_start
  changed_when: thrift_start.stdout.find('starting thrift') == -1
